package com.cube.model.generators

import com.cube.model.AnimationFrame

// simple gneerates that modifies the frames generated by another generator with a sine wave 
class XSinWaveSceneGenerator(sceneGenerator: SceneGenerator) extends SceneGenerator {

    var offset : Double = 0 
    
    def nextFrame() : AnimationFrame = {
        offset = if (offset > math.Pi*2)  offset - math.Pi*2 else offset+0.4
        val waveForm = sceneGenerator.nextFrame().points.map(p=>p.translate((Math.sin(offset+((p.x % 360) * math.Pi*2/360 )*40)*2.0).toInt,0,0))
        new AnimationFrame(waveForm)
    }    
}
